version = "33.3.3"

[iosevka-ttf]
variant = ""
name = "Default"
description = """
Monospace, Default fonts."""

[iosevka-aile-ttf]
variant = "Aile"
name = "Aile"
description = """
Quasi-proportional, Sans-serif fonts."""

[iosevka-etoile-ttf]
variant = "Etoile"
name = "Etoile"
description = """
Quasi-proportional, Slab-serif fonts."""

[iosevka-curly-ttf]
variant = "Curly"
name = "Curly"
description = """
Monospace, Curly fonts."""

[iosevka-curly-slab-ttf]
variant = "CurlySlab"
name = "Curly Slab"
description = """
Monospace, Curly Slab fonts."""

[iosevka-slab-ttf]
variant = "Slab"
name = "Slab"
description = """
Monospace, Slab fonts."""
